//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleriYönetimi.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtoGaleriYönetimiEntities : DbContext
    {
        public OtoGaleriYönetimiEntities()
            : base("name=OtoGaleriYönetimiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<Arabalar> Arabalars { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerUser> CustomerUsers { get; set; }
        public virtual DbSet<SatilanArabalar> SatilanArabalars { get; set; }
        public virtual DbSet<SatilikAraclar> SatilikAraclars { get; set; }
        public virtual DbSet<KiralikAraclar> KiralikAraclars { get; set; }
        public virtual DbSet<KiralanmisAraba> KiralanmisArabas { get; set; }
    }
}
