//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleriYönetimi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralanmisAraba
    {
        public int KiraNo { get; set; }
        public int MusteriId { get; set; }
        public string AdSoyad { get; set; }
        public int ArabaId { get; set; }
        public string GünlükFiyat { get; set; }
        public string KacGün { get; set; }
        public string ToplamÜcret { get; set; }
        public string KiralananTarih { get; set; }
    }
}
