//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoGaleriYönetimi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatilikAraclar
    {
        public int SatilikNo { get; set; }
        public int ArabaId { get; set; }
        public string Marka { get; set; }
        public string Plaka { get; set; }
        public string Model { get; set; }
        public string Vites { get; set; }
        public string Km { get; set; }
        public string Fiyat { get; set; }
        public string AracResim { get; set; }
    }
}
